export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";
export const RESET_CONTACTS = "RESET_CONTACTS";

export const UPDATE_SEARCH_KEYWORD = "UPDATE_SEARCH_KEYWORD";
export const UPDATE_ONLY_EVEN_FILTER = "UPDATE_ONLY_EVEN_FILTER";
export const UPDATE_PAGE_NO = "UPDATE_PAGE_NO";
export const INCREMENT_PAGE_NO = "INCREMENT_PAGE_NO";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
